### ISSUE TITLE
useObserve doesn't support returning a Promise?

### ISSUE THREAD

**Issue by mfbx9da4** [LegendApp/legend-state#112]
You might want to do something async

eg

```
useObserve(selectedId, async (id) => await updateFoo(id))
```

But the signatures don't support this

```
export function useObserve<T>(
    selector: ObservableReadable<T>,
    callback: (e: ObserveEventCallback<T>) => T | void
): void;
export function useObserve<T>(selector: (e: ObserveEvent<T>) => T | void): void;
export function useObserve<T>(selector: Selector<T>, reaction?: (e: ObserveEventCallback<T>) => T | void): void;
```

**Comment by jmeistrich** [comment]
This is updated in the latest RC version to use `any` instead of `void` for the return type. Please let me know if it's still not working right for you after updating. 

The RC version what we're currently using in production in two apps so it should be quite stable, but we're just tightening up some last things in the apps before releasing 1.0.

**Comment by mfbx9da4** [comment]
Could you clarify if an async `useObserve` [also has this caveat](https://twitter.com/DasSurma/status/1630600684646154240?s=20) that you have to read all observable values before you do anything async?

**Comment by jmeistrich** [comment]
Yes, it would have the same caveat for the same reason - it tracks observables accessed while running the function, so anything after an await would be run after it's stopped tracking.
