### ISSUE TITLE
Error 'Too many re-renders' with useObserve hook in versions 0.21.13 and above

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#119]
I was using version 0.21.10 of this library and everything was working fine. However, when I upgraded to the latest version, I received the following error message:

```
 ERROR  Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in Empty(RootComponent), js engine: hermes
```

To investigate the issue, I created a new empty project and added the legend-state library. I used the `useObserve` hook in the following way:

```tsx
import {useObserve} from '@legendapp/state/react';
import React, {useState} from 'react';
import {StyleSheet, Text, View} from 'react-native';

function App() {
  const [state, setState] = useState(0);

  useObserve(true, () => {
    setState(s => s + 1);
  });

  return (
    <View style={styles.container}>
      <Text>Hello World!</Text>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```
However, the same error occurred. After some trial and error, I discovered that this error only occurs in versions 0.21.13 and above. Could you please explain how the behavior of the useObserve hook has changed in these versions?

**Comment by matthewmturner** [comment]
@SMhdAsadi `useObserve` is meant to be used with observables (i.e. you can use `useObservable` instead of `useState` so I dont think you are using it in the intended manner.  Additionally, within the hook I believe it only tracks calls to `get` and rerenders when that variable changes.

In your case It looks like the hook is just in a loop of updating state and then picking up the change to state and rerendering again.  But again I think this isn't intended use as its not an observable and you aren't making a tracking `get` call.

Can you explain more about your use case and why you are using `useObserve` like this?

Maybe im missing something though.  @jmeistrich def the authority on this.

**Comment by SMhdAsadi** [comment]
I tried using all the rc versions, but encountered issues with each of them. However, the latest rc version released today (rc-32) has fixed the problem. Thank you!

**Comment by matthewmturner** [comment]
@SMhdAsadi if youre trying to have state and observables work together perhaps you could nest your hooks and have `useObserve` within another hook and only use it for accessing your observables.

**Comment by jmeistrich** [comment]
@SMhdAsadi Would you be able to share an example of how you're mixing useState with observables? In our projects we migrated components one by one converting everything fully from state to observables so we don't really mix useState and observables. But I am very curious to see how you mix them - we may be able to support it better or include the concept in a migration guide?
