### ISSUE TITLE
Question: what is the purpose of useObserveEffect?

### ISSUE THREAD

**Issue by macalinao** [LegendApp/legend-state#152]
Consider the following code:

```
  useEffectOnce(() => {
    observe(() => {
      console.log("observable changed in my hook", myObservable.get());
    });
  });
```

What is the benefit of using `useObserveEffect` instead? I see use of refs but it's not immediately clear to me what the use case is.

Furthermore, my code is updating the global `myObservable` somewhere else, and the `useObserveEffect` version does not get run. My broken example:

```
  useObserveEffect(myObservable, () => {
    console.log(
      "observable changed in useObserveEffect hook",
      myObservable.get()
    );
  });
```

What might be causing this? Thanks!

**Comment by jmeistrich** [comment]
The benefit is mainly the refs. Setting up the observe manually as in your code is totally fine, but if you used any local state there it would go out of date if the component renders again. The refs make it stable so that when the observe function runs again, it uses the current local state.

I'm not sure why that example wouldn't work. I just added a test for it and tested manually and it works. Can you share how you're creating the observable and setting it?

**Comment by jmeistrich** [comment]
I'm going to close this due to inactivity. If you can reproduce that bug feel free to re-open it.
