### ISSUE TITLE
Export types of `optimized` and `findIDKey` from globals

### ISSUE THREAD

**Issue by LukaszGrela** [LegendApp/legend-state#170]
Could the `optimized` and `findIDKey` be exported in types, this will help to reimplement `For` (possibly other as well) components. This will help with the #153 

e.g. if it belongs to `internal`
```
// ...
import { ensureNodeValue, get, getNode, peek, setNodeValue, optimized, findIDKey } from './src/globals';
import { getProxy, set } from './src/ObservableObject';
export declare const internal: {
    // ...
    findIDKey: typeof findIDKey;
    optimized: typeof optimized;
};
```

or just if it is not part of internal
```

export {optimized, findIDKey} from './src/globals'
```

**Comment by jmeistrich** [comment]
Yes, that's a good idea. I added them to `internal` in 1.9.0-next.1.

I have been meaning to get to #153 though, I've just been busy with other things. If you want to submit a PR that makes that work as you want, that might be better than reimplementing it separately? The blocking point for me is mostly in writing the tests to ensure it's correct because I'm not 100% sure what it would be expected to do. So even submitting a PR with failing tests would be helpful 😀
