### ISSUE TITLE
Chaining useComputed doesn't work when there is a dependency array

### ISSUE THREAD

**Issue by axtgr** [LegendApp/legend-state#188]
In a react component, I have a useComputed that depends on another useComputed that depends on a regular state variable via the second argument of useComputed. I expect both computeds to update whenever the state changes, but only the first one updates.

Here is the code ([sandbox](https://codesandbox.io/s/adoring-wind-9ndhh4?file=/src/App.js)):

```
import { useState, useEffect } from "react";
import { useComputed } from "@legendapp/state/react";

export default function App() {
  const [counter, setCounter] = useState(0);

  // Reacts to counter updates
  const computed1 = useComputed(() => ({ counter }), [counter]);

  // Doesn't react to counter updates
  const computed2 = useComputed(() => ({ counter: computed1.counter.get() }));

  useEffect(() => {
    const interval = setInterval(() => {
      setCounter((i) => ++i);
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <div>computed1: {computed1.counter.get()}</div>
      <div>computed2: {computed2.counter.get()}</div>
    </>
  );
}
```

In this component, only the first computed updates when the counter iterates. I'm pretty sure this happens because under the hood useComputed uses useMemo that _creates a new computed each time the dependencies change_: 

```
return useMemo(
    () =>
        computed<T, T2>(
            () => (isFunction(ref.current.compute) ? ref.current.compute() : ref.current.compute) as T,
            (set ? (value) => ref.current.set!(value) : undefined) as (value: T2) => void,
        ),
    deps || [],
);
```

The second computed is never updated because it doesn't have dependencies and it keeps a reference to the initial version of the first computed forever.

Is this the expected behavior? If so, what would be the proper way to do this?

**Comment by jmeistrich** [comment]
The main problem is that I think you're expecting `useComputed(() => ({ counter }), [counter])` to create a single `computed` and update itself when state changes, but that's not how `computed` works. [computed](https://legendapp.com/open-source/state/observable/#computed) computes its value based on other observables. So giving it a state value and a deps array like that is just creating a static read-only observable with that value every update.

And you're right, that's part of why the second one is not updating, because it's using the one created on the first render. But also, computed1 is never getting updated to anything because it's not being set anywhere, so the second one would never update anyway. I would suggest to just remove the `useState` here.

Also, `get()` does not automatically track and re-render, so after taking `useState` out, this would only render once. You would want to use [.use()](https://legendapp.com/open-source/state/react-api/#observer-hoc) instead of `.get()` or wrap the component in [observer](https://legendapp.com/open-source/state/react-api/#observer-hoc) to make it re-render when the observable changes.

Forked sandbox: https://codesandbox.io/s/wild-shape-zwh35r?file=/src/App.js

```jsx
import { useEffect } from "react";
import { useComputed, useObservable } from "@legendapp/state/react";

export default function App() {
  const counter$ = useObservable(0);

  // Reacts to counter updates
  const computed1 = useComputed(() => ({ counter: counter$.get() }));
  
    // Reacts to computed1 updates
  const computed2 = useComputed(() => ({ counter: computed1.counter.get() }));

  useEffect(() => {
    const interval = setInterval(() => {
      counter$.set((i) => ++i);
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <div>counter: {counter$.use()}</div>
      <div>computed1: {computed1.counter.use()}</div>
      <div>computed2: {computed2.counter.use()}</div>
    </>
  );
}
```

**Comment by axtgr** [comment]
Thanks for the quick reply! 

Yeah, I'm aware of everything you said, but I need counter to be a regular variable inside a component and have a stable observable that updates every time the variable changes in a render. I see that there is `createObservableHook`, which may work in my case, but it sounds hacky. Is there another way to do this?

Computed seemed like it could've been a good fit, but as it turned out, the current implementation doesn't work like that. By the way, the dependency array [isn't documented](https://legendapp.com/open-source/state/react-api/#usecomputed), so it wasn't clear what it's for. What's the purpose of recreating the computed?

**Comment by axtgr** [comment]
My use case is that I have a code base that I don't want to refactor to observables all at once. There is a hook that uses context and state and whatnot and returns a value. I don't want to touch that hook. There is also a hook that I've already refactored. Now it accepts an observable as an argument and uses it inside `useComputed`. Inside a component, I want to use the first hook, create an observable based on the returned value and pass the observable to the second hook. Something like this:

```
function useFirstHook() {
  const [value, setValue]= useState({ foo: 'bar' })
  return value
}

function useSecondHook(observable$) {
  const computed$ = useComputed(() => ({ ...observable$.get(), baz: 'qux' }))
}

function App() {
  const value = useFirstHook()

  // If this created a stable computed that updated its value whenever deps change,
  // it would be a nice way to create a bridge between the old code and the new code
  const parameter$ = useComputed(() => value, [value]) 

  useSecondHook(parameter$)
}
```

**Comment by jmeistrich** [comment]
Ah, I see. 

In that case I think you want to create an observable with `useObservable` and just update it whenever state changes. You could try one of these hooks?

Or ideally, wherever you `setValue` on the first hook you could set the observable value at the same time. The problem with updating based on state changing is that you're already mid-render. So it's possible React would complain about the first one triggering another component rendering during render, in which case the useEffect version might be better, but it may have a delay of a frame because it would run after render.

```tsx
import { type Observable } from '@legendapp/state';
import { useObservable } from '@legendapp/state/useObservable';
import { useEffect } from 'react';

export function useObservableUpdatedWithState<T>(value: T): Observable<T> {
    const obs$ = useObservable(value);
    obs$.set(value);
    return obs$;
}

export function useObservableUpdatedWithStateEffect<T>(value: T): Observable<T> {
    const obs$ = useObservable(value);
    useEffect(() => {
        obs$.set(value);
    }, [value])
    return obs$;
}
```

**Comment by jmeistrich** [comment]
Oh and the deps array on useComputed is for rare cases where the observables to be tracked changes. It's actually only used once across all of Legend and Bravely, which speaks to how rarely it would probably be used . We might even want to think about changing that one usage and removing the deps array to make it less confusing... Here's a contrived example:

```tsx
function useDate(obs$: Observable<number>) {
    return useComputed(() => {
        return new Date(obs$.get());
    }, [obs$]);
}

function App() {
  const [which, setWhich] = useState(false)
  const time1$ = useObservable(Date.now())
  const time2$ = useObservable(Date.now() - 100000)
  // Change which observable to use based on an option
  const date$ = useDate(which ? time2$ : time1$);

  return <div />
}
```

**Comment by axtgr** [comment]
Thanks for the detailed explanation and suggestions!
