### ISSUE TITLE
Computed observables are not garbage collected and are always evaluated

### ISSUE THREAD

**Issue by simontreny** [LegendApp/legend-state#202]
Hi,

First of all, thanks a lot for making this library open source, I really like it, especially its API that I find really well designed. 🙌 

I'd like to share what I think is an issue with the current implementation of `computed()` observables: because they are referenced by their dependencies (i.e. the observables on which `.get()` is called while the computed observable is evaluated), they won't be garbage collected even if they are no longer used. It will lead to memory leaks for any computed observables that do not have the same lifetime as the app.

Another related issue that could cause performance issues is that computed observables are re-evaluated whenever one their dependencies changes, even if they are no longer being observed. Because of that, `computed()` can't really be used to create computed observables dynamically.

Here is an example:
```tsx
const users = observable<{ id: number; firstname: string }[]>([
  { id: 0, firstname: "John" },
  { id: 1, firstname: "Alice" }
]);

function getUserById(id: number) {
  return computed(() => {
    console.log(`Finding user with id ${id}`);
    return users.get().find((user) => user.id === id);
  });
}

export function UserProfile({ userId }: { userId: number }) {
  const user = useSelector(() => getUserById(userId));
  ...
}
```

Every time `UserProfile` gets re-rendered, it creates a new computed observable. These observables will never be garbage collected because they are referenced by `users`. Also, every time `users` is modified, all computed observables created since the launch of the app will be re-evaluated while only a single one is being observed for each mounted `<UserProfile>`.

**Expected behavior:**
* Only computed observables that are being observed should be re-evaluated
* Computed observables that are no longer referenced should be garbage collected

I've implemented my own observable library and I think the proper way to fix that is to "connect" computed observables to their dependencies only when they are observed (and disconnect them when it's no longer the case). This makes the implementation a bit complex to write. I believe this is also how [Preact Signals](https://github.com/preactjs/signals/blob/main/packages/core/src/index.ts) are implemented

**Comment by jmeistrich** [comment]
Yes you're right, we should have a way for computeds to disable themselves when there's no more listeners. They already activate lazily, so when the last listener is removed they could revert to an unactivated. However, it's not super simple because listeners are removed and added quite often when re-evaluating, so there would need to be a cleanup pass at the a batch. I'll look into that.

In your example though, it really shouldn't be creating a new computed every time. In fact you could just remove it and it should work as you expect. `useSelector` is kind of like a `computed` in itself - it will re-run whenever any accessed observables change and re-render the component whenever its returned value changes.

Example with just the computed removed:
```ts
const users = observable<{ id: number; firstname: string }[]>([
  { id: 0, firstname: "John" },
  { id: 1, firstname: "Alice" }
]);

function getUserById(id: number) {
  console.log(`Finding user with id ${id}`);
  return users.get().find((user) => user.id === id);
}

export function UserProfile({ userId }: { userId: number }) {
  const user = useSelector(() => getUserById(userId));
  ...
}
```

But it absolutely is a problem if a component has a `useComputed` and it unmounts. So we should definitely fix this.

**Comment by simontreny** [comment]
> In your example though, it really shouldn't be creating a new computed every time. In fact you could just remove it and it should work as you expect

Agreed, using `computed()` in this example was needlessly complex. But I think this usage of `computed()` should still be allowed as it has some benefits:
* It could act as a memoization for complex computations (a bit like `useMemo()`). Not sure this is implemented currently.
* It prevents some unnecessary re-renders. If I append a new user to `users`, I would expect `UserProfile` to not be re-rendered as the value of the computed observable won't change. It wouldn't be the case without `computed()` as `users` would be a direct dependency of `UserProfile`.

**Comment by jmeistrich** [comment]
I just released version 3 alpha which includes computed auto-deactivating. They now only re-compute themselves while actively observed. Otherwise they are marked as dirty and will re-compute on the next get/peek.

So I’m going to close this issue as solved :). But please let me know if it doesn’t seem complete to you.
