### ISSUE TITLE
How do I break a store up across multiple files

### ISSUE THREAD

**Issue by johnwheeler** [LegendApp/legend-state#207]
I have read in another post that you do not support nested observables.

Passing state into a function that creates state that can later be merged into an observable doesn't seem to work

```
const selectionStore = (state$) => {
  return {
      createEmptySelection() {
        const timeline = state$.timeline.get()  // this is undefined
```

I'm trying to do something like

```
  const state$ = observable({ video: {}, timeline: {}, selection: {} })
  const video = videoStore(state$, initProps)
  const timeline = timelineStore(state$)
  const selection = selectionStore(state$)
  state$.assign({ selection, timeline, video })
```

Ideally, I want the video, timeline, and selection to all be able to access each other via state$.video.get, etc.

This is I guess similar to zustand slices. The end goal is to split multiple stores across multiple files.

**Comment by jmeistrich** [comment]
It's a little hard to tell without a full code sample, but I think you want to set the `state$` directly in the store initializers? If you don't assign until the end, it will all be undefined in the initializers?

```js
const videoStore = (state$) => {
  state$.video.set({ initialVideoProperty: true })
}
```

**Comment by jmeistrich** [comment]
Ah I see. Setting `computed` into an observable currently only works at initialization time, so that won't work if you `set` with it later. We're working on a big revamp to computeds which will make that work. Our original design didn't support all the different ways people wanted to use computed so it's gotten a bit hacky as features like computed children were added.

I'd suggest two alternatives for now:
1. Just have the states be separate stores. Unless it's crucial that they all be contained within the same store, just have each file export its own store. It's totally fine for a store to reference another. This is what we do in Legend and Bravely (the two apps Legend-State was built for).
2. Change `state$` to be just an object instead of an observable, and put observables at child keys similar to what you're doing now. Then you'd have access to all stores within it.

**Comment by jmeistrich** [comment]
@johnwheeler That's so great to hear 🥰

I just realized that setting computeds does work in version 2.0. So you could try that in 2.0.0-beta.8 if you'd like. We're planning to release 2.0 on Monday so there are unlikely to be any more changes :)

**Comment by shovel-kun** [comment]
@johnwheeler Hi there, may I know what approach you're using for multiple stores? (If you're still using `legend-state`, that is). I'm migrating from `mobx-state-tree` and having a global root store with multiple children stores is what I'm used to.

**Comment by jkcorrea** [comment]
Just checking comments on this issue
