### ISSUE TITLE
useSelector won't return functions in store

### ISSUE THREAD

**Issue by briandipalma** [LegendApp/legend-state#213]
If you put functions in your store and use useSelector to get them you won't have them returned.

I'm guessing it's due to

```typescript
export function computeSelector<T>(selector: Selector<T>, e?: ObserveEvent<T>, retainObservable?: boolean) {
    let c = selector as any;
    if (isFunction(c)) {
        c = e ? c(e) : c();
    }

    return isObservable(c) && !retainObservable ? c.get() : c;
}
```

We are doing this as we are moving from a zustand store to legend-state. And we'd prefer to make minimal changes so we're still using the store actions to update the store state.

```typescript
export function useTile<T>(
  selector: (state: TileStore) => Observable<T> | T
): T {
  const store = useContext(TileContext);

  if (!store) {
    throw new Error("Missing TileContext.Provider in the tree");
  }

  return useSelector(selector(store));
}
```

this is the hook we're using in our component. This is what the store looks like:

```typescript
  const store = observable({
    ...
    setCurrencyPair: (currencyPair: string) => store.assign({ currencyPair }),
    setESPConfigData: (data: EspConfigData) => espData.assign(data),
    ...
  });
```

When we run

```typescript
  const setESPConfigData = useTile((s) => s.setESPConfigData);
```

setESPConfigData is not the function we expect.

We're currently working around this by doing:

```typescript
function isObservable<T>(key: Observable<T> | T): key is Observable<T> {
  return (key as Observable<T>)?.get !== undefined;
}

export function useTile<T>(
  selector: (state: TileStore) => Observable<T> | T
): T {
  const store = useContext(TileContext);

  if (!store) {
    throw new Error("Missing TileContext.Provider in the tree");
  }

  const storeMember = useSelector(() => selector(store));

  if (isObservable(storeMember)) {
    return storeMember.get();
  }

  return storeMember;
}
```

Not sure if there is a good solution to this as I imagine you can't really change the computeSelector logic but maybe further up the callstack you can short circuit the code and return values from store if they are functions. Unless maybe functions should be wrapped in Proxys too? What happens if the function in the store is updated? Will any observers be notified?

**Comment by jmeistrich** [comment]
I think the issue is that the functions are extracted from the raw object and saved as metadata inside the observable, so you can call the functions through the observable but not on the raw object. This is done for a few reasons, the main being that you can put an async function into an observable and it will await the promise and then fill itself with the resolved data. 

So since `computeSelector` gets the raw object, the function isn't actually there.

We should fix this within `computeSelector`. I've got a prototype in progress, but it's so core that I want to add more tests before releasing it. I'll try to get a fix out today.

By the way, you can `import { isObservable } from '@legendapp/state';` which is more accurate for that purpose.

**Comment by jmeistrich** [comment]
Actually it might be a tough one... I'm working on some new concepts where it becomes unclear what `computeSelector` should do in this situation. I'll have a think about the best way to approach it.

What version are you using? The behavior of functions changed a bit between v1 and v2.

**Comment by briandipalma** [comment]
v2, after you added React as an optional peer dependency. No stress about this issue, we have a workaround. I just wanted to make you aware of it.
