### ISSUE TITLE
For component not re rendering when a key id removed from an object

### ISSUE THREAD

**Issue by levic92** [LegendApp/legend-state#250]
I am using the `For` component to render a list of objects
`<For each={reports$.all} item={Row} sortValues={(aa, bb) => bb.id - aa.id} />`

The observable is:

```
type TReportData = {
    type: string;
    firstName: string;
    lastName: string;
};
type TReportStore = {
  all: Record<number, TReportData>;
};
export const reports$ = observable<TReportStore>({
  all: {},
});
```

When I call `reports$.all[id].delete();` in a react component there is no re render, and the item stays in the list on the screen even though the data was deleted.

If in that same component I add `const all = reports$.all.get();` anywhere in there, then the list on screen is updated when the item is deleted.

**Comment by jmeistrich** [comment]
I believe this should be fixed in 3.0. I wrote a test to check `delete` and it passes it now. https://github.com/LegendApp/legend-state/blob/bdedbd997f484fa1de76ea8e15684905a0f16f49/tests/react.test.ts#L633

Can you please try updating to the latest alpha version and let me know if it’s still a problem?
