### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#266]
1.  `observer()` type is not right, it is based on FC which is based on `Element<any,any>` instead of `Element`. Correct type to my opinion is the one used in `memo()`. (React.FC was considered for long as not recommended type).
2. `computed(()=>xxx$.find())` returns a type which includes `& ObservableComputedFnsRecursive` as oppose to `computed(()=>xxx$.filter())`, which returns simpler type. Additionaly `ObservableComputedFnsRecursive` is not exported from the lib. But better the type to be simple.

**Comment by jmeistrich** [comment]
1. I’ve changed that for the upcoming v3 and it seems much more correct in my testing: https://github.com/LegendApp/legend-state/blob/343ff54a5be431b47bd428df2b3d7a8c50f2c54f/src/react/reactive-observer.tsx#L163
2. I think the problem with `computed(()=>xxx$.find())` is that `xxx$.find()` returns an observable, so that makes a computed of an observable. That will be fine in v3, but I think it’s not what you want here. Doing a `get()` first should make the types correct: `computed(()=>xxx$.get().find())`.
3. That was a design mistake I made, making “state” a special reserved property of persisted observables. v3 will fix that.

**Comment by jmeistrich** [comment]
I believed these are all fixed in version 3 so I’m going to close this issue. Thank you for catching those problems :)
