### ISSUE TITLE
`persister.state.isLoadedLocal` is not typed correctly sometimes

### ISSUE THREAD

**Issue by nightire** [LegendApp/legend-state#289]
Not sure if this is a known issue, but I have a test case here:

https://www.typescriptlang.org/zh/play/?target=99&ts=5.4.5#code/JYWwDg9gTgLgBDAnmApnA3nA8gIwM4pQBuAhjgDYq4BWKAxjADRwDqwMAFgAqF7B4wAyjBIw0AXzgAzKBBBwARAAFKAcxQA7ACYkwYAPQDRKBQChTwDWKhSSdNABUUAgMIkCARgym4v6RAgALjgBKEtVU3FzJFQ4J1d3FAAmOABeOAAlemgtAB5Q8OYCjVUAPnNLa1t7OOcYNwIAZm8-OABtAGsURGDi1QBdXpgwksjzLXpyEig0OggNAQQ6j2DcAmIyShp6GFy2Th4oPgFhYzgAMlqEz3LTMQEPADojMQB+R-4AGQgSCa1vugkcimfT6Vrg3wAPVe40m01m80W9xgSVW+EIpAoVBwtAYe3Y3F4-CEIjEFyu9USSVuyKSz1JKHeXx+fwBQJBYIhrWhsLoUxmcDmC3gyMaaPWmK2OJ2+IORJODPJ8UpTRpdUa9OMTLw31+KH+EEBwNBXO5MKAA

In brief, the returned type of `persistObserveable<T>` is not correctly typed `state` if `T` is `Record` or an indexed signature object.

**Comment by jmeistrich** [comment]
It was basically just a bad idea to add a `state` property to the observable. So in version 3 we’ve changed it so that `state` is created separately and accessible through `syncState`: https://legendapp.com/open-source/state/v3/sync/persist-sync/#syncstate

So this should be fixed in version 3 now, but please let me know if you still see any issues around it.
