### ISSUE TITLE
How to be reactive to size of Map

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#322]
`m$.size.get()` does not do the trick
https://stackblitz.com/edit/vitejs-vite-flkj8c?file=src%2FApp.tsx
`m$.get(true)` will not work because true is a map key

**Comment by BalogunofAfrica** [comment]
I think the order is wrong you can either get the map observable first and then get the size of the map. 

```ts
m$.get().size
```

Or you can create a computed value for the size

```ts
const s$ =computed(() => m$.get().size)
```

**Comment by lishine** [comment]
The whole point is that I want to be reactive to size only and not to the whole map.

**Comment by jmeistrich** [comment]
Fixed in alpha.22. It could be a breaking change if you were using `size.get()` but it seems like it wasn't working well anyway. I think it's more correct if `size` is a number rather than an Observable to match the native Map/Set API.

So now `m$.size` will return a number as expected, but it will set up shallow tracking.

I think we should not support `m$.get(true)` as a way to do shallow tracking because we might accidentally break someone trying to use a Map with a boolean value. That means the use case of doing a shallow get on a Map can be done as a two step:

```js
map$.size // Shallow track
map$.peek() // Get data without tracking
```

But I wonder if we can do better? What do you think? Or is this fine (for now)?

**Comment by lishine** [comment]
Yes, I think it is good. Thanks
But then do the same for array length?

**Comment by jmeistrich** [comment]
Array length should already do that. Is it not working right in some case?

**Comment by lishine** [comment]
It was something wrong with my repro, because in v3 from the beginning size is number and reactive as oppose to v2.
And so do length as oppose to v2 where it was not reactive.
But look, something about set of Map is wrong. As if it working, but the type not:
https://stackblitz.com/edit/vitejs-vite-flkj8c?file=src%2FApp.tsx

**Comment by nouman2075** [comment]
> It was something wrong with my repro, because in v3 from the beginning size is number and reactive as oppose to v2. And so do length as oppose to v2 where it was not reactive. But look, something about set of Map is wrong. As if it is working, but the type not: https://stackblitz.com/edit/vitejs-vite-flkj8c?file=src%2FApp.tsx

I'm facing the same error related to type after updating to 3.0.0-alpha.22

**Comment by jmeistrich** [comment]
Oh yikes, the type of ObservableMap's value was wrong. Should be fixed in alpha.24.
