### ISSUE TITLE
When to use indexedDB persistence vs. localStorage?

### ISSUE THREAD

**Issue by warrenbhw** [LegendApp/legend-state#326]
Do you have any guidance on reasons why one should choose indexedDB persistence over localStorage? It seems like localStorage is simpler, but I assume that there is some cost (doesn't cope well with schema changes, or bad perf as your DB gets larger)

**Comment by jmeistrich** [comment]
It's basically a perf consideration. localStorage is fine for small data but with large data it could freeze the UI while it saves/loads. On the other hand, since IndexedDB is async you have to wait for it to load, so for small data localStorage may be faster.

Since legend-state has a strategy of loading everything into memory, the querying capabilities of IndexedDB are less important, so it's more of a save/load time and sync/async consideration.

**Comment by MCW77** [comment]
There is also some situations where you don't have access to localStorage but indexedDB is still working (ex: in a worker thread)
