### ISSUE TITLE
Array.find has strange behaviour/updates

### ISSUE THREAD

**Issue by mkhennoussi** [LegendApp/legend-state#333]
Hi everyone, I hope you are doing well.

I found a strange behaviour when I use Array.find method, I'm not sure what's happening.

Here is a demo : https://stackblitz.com/edit/react-starter-typescript-bjbywy?file=App.tsx,store.ts

If you click on the button "Select", it will select an estimation and print its id above. 
Then click delete : 

- If you use the following code, the selected id above takes the next one in the estimation array : 
  ```js
  estimationSelected: () =>
     appState$.estimations.find(
      (e) => e.id.peek() === appState$.estimationIdSelected.get()
     ),
  ```  
- If you use this code, the id is removed and works as expected : 
```js
  estimationSelected: () =>
    {
      let index = appState$.estimations.findIndex(
        (e) => e.id.peek() === appState$.estimationIdSelected.get()
      );
      return appState$.estimations[index];
    }
```
The only thing happening with `estimationIdSelected` is `estimationIdSelected.set('')` in the deleteEstimation method.

Why the code behaves like if I was doing `estimationIdSelected.set(// next item in the array)` ?

Any idea why this is happening guys ?

Thanks and hope it can helps !

**Comment by jmeistrich** [comment]
Thanks @mkhennoussi, I used your example to write a failing test and will try to fix it.

Basically what's happening is that it first creates a direct link to the array at index 0. Then when you delete the element at index 0 it's still referencing the observable at index 0.

Of course this should be fixed but for now I think in your example it would be much better to use an object keyed by id. Like:

```ts
 interface AppState {
    estimations: Record<string, Estimation>;
    estimationIdSelected: string;
    estimationSelected: Estimation;
}
```

Then you wouldn't need to find by id, because that's easy in a record. And the observable linking would behave correctly because you'd have an observable pointed to an id instead of an index in an array.

**Comment by mkhennoussi** [comment]
Ok thanks @jmeistrich , it makes perfectly sense to me !

**Comment by jmeistrich** [comment]
This should be fixed in alpha.27. Thanks for the report! I'll close the issue but please reopen it if it's still not working right.
