### ISSUE TITLE
V3: Reactive typings are completely broken

### ISSUE THREAD

**Issue by BorisZubchenko** [LegendApp/legend-state#370]
The example is taken from [the docs](https://legendapp.com/open-source/state/v3/react/fine-grained-reactivity/#reactive-components)
![image](https://github.com/user-attachments/assets/9a38199d-f8d4-4774-bfd1-72163953b33d)
```
    "@legendapp/state": "^3.0.0-beta.8",
```

**Comment by jmeistrich** [comment]
Thank you! In a recent update I had improved Reactive to be enabled per-platform automatically, but it seems it's not possible for the types to enable automatically in the same way. They appeared correct in my apps because there was a hidden file still calling the old config functions 😅.

So with beta.9 there's now just one file you need to import anywhere in your codebase, or ideally in a `.d.ts` file:

```ts
import '@legendapp/state/types/reactive-web';
```

I added that to the docs: https://legendapp.com/open-source/state/v3/react/fine-grained-reactivity/#reactive-types
