### ISSUE TITLE
`getPrevious` does not work for Array changes

### ISSUE THREAD

**Issue by Manc** [LegendApp/legend-state#39]
First, thank your for your great work! I'm currently trying to integrate this library into my new web app – and trying to get my head around the concept/usage and the types. I do have a few issues understanding, but one thing at a time. I'm using React.

I have an `Array` of items that can be rearranged by the user. I use `state.onChange` and its `getPrevious()` function to look for certain changes. If I deal with content changes (e.g. strings), `getPrevious()` works as expected, giving me the state as it was before the change. However, when changing the order of `Array` items, the result of `getPrevious()` and the current state are the same.

I have created a [Sandbox example](https://codesandbox.io/s/legend-w-observable-forked-mjsd91?file=/src/App.tsx). To verify the issue, please click the *Up* and *Down* buttons to rearrange the items, and check the Console logs; before/after should be different, but are equal.

**Comment by Manc** [comment]
I think I found the cause of the problem myself. In my example, in line 70 I `get()` the array, then modify it direcly, then `set()` it. If I make a copy of the array that I get from `get()` (e.g. `const items = [...obs.list.get()]`), it works as expected. By modifying the array in my code (lines 72-73), I seem to modify directly what's in the state. I guess I can close this issue myself, but it still leads to #41 as I'm still struggling a bit to understand how one is supposed to modify an array properly.

**Comment by jmeistrich** [comment]
Hmm yes, this can be improved. It does save a copy of the original array before applying the change so we should be able to pipe that through to `getPrevious`. I'll reopen this because it should be fixable.

**Comment by jmeistrich** [comment]
Digging into this a bit further I realize I hadn't originally looked closely enough at your example. As you said, since `get()` returns the original array, modifying it modifies the array in state, so when you call `set` you're setting it to what it already is. 

I don't think there's anything to fix there since we don't want to be cloning on `get()` so I think we just need to clarify it in the docs, unless you think there's a potential improvement to be made? So I'll close this issue and work on improving the docs for https://github.com/LegendApp/legend-state/issues/41.

**Comment by Manc** [comment]
As far as I remember, the Redux docs were very clear that objects/arrays should always be copied before merging changes into the state or even before using/modifying them. It would probably make sense to stress that in the docs here too. Maybe get() and peek() should even return a Readonly type?
