### ISSUE TITLE
Add index to function in `For` component

### ISSUE THREAD

**Issue by Manc** [LegendApp/legend-state#40]
I'd find it convenient if the `For` component would expose an item index, similar to what `Array.map`, `Array.forEach`, etc. do in JavaScript. I don't know if there is a reason for not having it.

In my [Sandbox example](https://codesandbox.io/s/legend-w-observable-forked-mjsd91?file=/src/App.tsx) I use `useSelector()` to build a `Map` to map the IDs of Array objects to their current index numbers. This seems overly complicated.

**Comment by jmeistrich** [comment]
Hmm yes, that would certainly be more convenient! It doesn't currently provide the index because in the `optimized` behavior the element can re-render itself at a new index without the parent list rendering, which means the For component can't provide a reliable index prop to the child. I'll try to figure out another way to do it. The observable node knows its own index so it should be possible - just need to find the right way to expose it.

**Comment by jmeistrich** [comment]
@Manc I added a `getObservableIndex` function in version `0.21.5`. Let me know how that works for you 😀

**Comment by Manc** [comment]
Thank you very much! I'm upgrading now. Will let you know shortly. :)

**Comment by Manc** [comment]
I've upgraded the package in my project and used the new `getObservableIndex` – it works perfectly. Thank you!
