### ISSUE TITLE
Component not rendering when using get() in react 19

### ISSUE THREAD

**Issue by nouman2075** [LegendApp/legend-state#420]
When using enableReactTracking and get(), component does not render when using react 19.
It works fine in react 18 and with react 19 when wrapped with observer()

https://codesandbox.io/p/sandbox/nywrhq?file=%2Fsrc%2FApp.tsx%3A20%2C14

**Comment by jmeistrich** [comment]
enableReactTracking does not work in React 19. The documentation for it warns about that: https://www.legendapp.com/open-source/state/v3/usage/configuring/#enablereacttracking

We're actually about to fully deprecate it and encourage using `useSelector` instead of this or `observer`, to work better with React 19 and the Compiler.

Are there still parts of the docs that encourage using enableReactTracking? I am doing a big pass across the docs right now to fix any mistakes and change the guidance to encourage `useSelector`.
